require 'rake'
require 'rspec'
require 'rspec/core/rake_task'
require 'ci/reporter/rake/rspec'

desc "Run specs"
RSpec::Core::RakeTask.new do |t|
  t.pattern = "**/*_spec.rb"
  t.rspec_opts = ["--format", "documentation", "--colour"]
end

desc "Run specs using Coverage tool"
RSpec::Core::RakeTask.new("spec:cov") do |t|
  t.pattern = "**/*_spec.rb"
  t.ruby_opts = ["-r 'simplecov'"]
end

desc "Run specs producing results for CI"
task "ci" => ["ci:spec"]

namespace :ci do
  task "spec" => ["ci:setup:rspec", "^spec:cov"]
end
