require 'rake'

desc "Package test apps"
task "package" => ["bundler:package"]

namespace "bundler" do
  task "package" do
    Dir['*/'].map { |asset|
      puts "Packaging #{asset}"
      Dir.chdir(asset) do
        sh("rm -rf vendor")
        sh("bundle install && bundle package")
      end
    }
  end
end
