require 'rake'

desc "Package test apps"
task "package" => ["bundler:package"]

namespace "bundler" do
  task "package" do
    Dir['*/'].map do |asset|
      puts "Packaging #{asset}"
      Dir.chdir(asset) do
        sh("BUNDLE_GEMFILE='./Gemfile' bundle install && bundle package")
      end
    end
  end
end