require "bundler/gem_tasks"
require 'rake'
require 'ci/reporter/rake/rspec'

desc "Run specs"
task "spec" => ["bundler:install", "test:spec"]

desc "Run specs using RCov"
task "spec:rcov" => ["bundler:install", "test:spec:rcov"]

desc "Run specs producing test results for CI"
task "ci" => ["ci:spec"]

namespace "bundler" do
  desc "Install gems"
  task "install" do
    sh("bundle install")
  end
end

namespace "test" do
  task "spec" do |t|
    sh("cd spec && rake spec")
  end

  task "spec:rcov" do |t|
    sh("cd spec && rake spec:rcov")
  end
end

namespace :ci do
  task "spec" => ["ci:setup:rspec", "^spec"]
end
