require 'rake'
require 'rspec'
require 'rspec/core/rake_task'
require 'ci/reporter/rake/rspec'

desc "Run specs"
task "spec" => ["test:package","test:spec"]

desc "Run specs producing results for CI"
task "ci" => ["ci:spec"]

namespace "test" do
  task "spec" do |t|
    RSpec::Core::RakeTask.new do |t|
      t.pattern = "spec/**/*_spec.rb"
      t.rspec_opts = ["--format", "documentation", "--colour"]
    end
  end

  task "package" do |t|
   sh("cd spec/assets && rake package && cd ../../")
 end
end

namespace :ci do
  task "spec" => ["ci:setup:rspec", "^spec"]
end